language: go

go:
  - 1.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - make install

script:
  - make lint
  - make test

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always
